spring:
  application:
    name: "tableorganizer"
  datasource:
#    url: jdbc:h2:mem:organizer
    url: jdbc:h2:file:./data/organizer
    username: glaitozen
    password: "zAwA120"
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

discord:
  token: 'our-token-discord-here'
